### ISSUE TITLE
[M0-Dev]Implementación del modelo de los usuarios del sistema

### ISSUE THREAD

**Issue by MarinoFajardo** [aacosa34/Keikaku#11]
Buenas @aacosa34, continuando con el proyecto voy a crear las clases necesarias para representar el modelo del problema, en este caso yo he identificado dos clases, una clase currículum y una clase oferta. Si es lo que tenías pensado te sigo comentando acerca de estas clases. Un saludo y que pases un buen finde.

**Comment by adacosdev** [comment]
Hola @MarinoFajardo! Mira en principio tengo en mente esas dos clases que comentas, pero me tengo que comer el coco para visualizar cómo Hortensia va a usar el servicio porque no sé si será conveniente hacer una clase usuario para que el personal de recursos humanos se autentifique para poder usar el servicio (ya que si no podría entrar cualquiera).

**Comment by adacosdev** [comment]
Buenas! Lo primero es que lo he pensado y es conveniente que se realice una clase para poder autenticar al personal de recursos humanos, ya que si no podría entrar cualquier persona a tocar los currículums. Así que habría que hacer un fichero con una clase para ello.

Y lo segundo es que para cada clase o modelo que necesites implementar me parece que hay que realizar un issue a parte, para que si quieres vayas abriendo algunos de los que ya sepas. Gracias!

**Comment by MarinoFajardo** [comment]
Perfecto @aacosa34, pues la primera clase que voy a realizar en este issue es esta que me comentas de recursos humanos y para las demás creo issues distintos. En cuanto a esta clase que me comentas quiero pedirte una serie de aclaraciones:
-¿Estos usuarios de recursos humanos van a tener distintos privilegios? Es decir, si va a haber distintos tipos de usuarios para crear una variable que nos represente estos tipos con un enumerado.
-¿Qué atributos van a tener estos usuarios? Yo había pensado los típicos de nombre, apellidos, fecha de nacimiento, privilegio, etc.
Un saludo.

**Comment by adacosdev** [comment]
>  -¿Estos usuarios de recursos humanos van a tener distintos privilegios? Es decir, si va a haber distintos tipos de usuarios para crear una variable que nos represente estos tipos con un enumerado.

Puesto que este sistema está pensado únicamente a personal de recursos humanos, los privilegios serán los mismos para todo el personal que use el sistema.

> -¿Qué atributos van a tener estos usuarios? Yo había pensado los típicos de nombre, apellidos, fecha de nacimiento, privilegio, etc. Un saludo.

Proponme una solución y te digo mi opinión, ¿vale? En principio serán los típicos. Muchas gracias! :smile:

**Comment by MarinoFajardo** [comment]
En este caso he creado la clase con los siguientes atributos:
-nombre:string 
-apellidos:string
-fecha_nacimiento:Date
-email:string;
-password:string
Todas las variables las he declarado como privadas. He creado también el constructor de la clase. En este caso he implementado la variable fecha_nacimiento como un Date aunque se podría haber implementado como un string. ¿Cambio algo o te parece correcto? Los getters y los setters no los he añadido puesto que como estamos realizando un pmv y en estos momentos del desarrollo no son necesarios no creo que sea conveniente añadirlos.

**Comment by adacosdev** [comment]
> En este caso he creado la clase con los siguientes atributos: -nombre:string -apellidos:string -fecha_nacimiento:Date -email:string; -password:string Todas las variables las he declarado como privadas. He creado también el constructor de la clase. En este caso he implementado la variable fecha_nacimiento como un Date aunque se podría haber implementado como un string. ¿Cambio algo o te parece correcto? Los getters y los setters no los he añadido puesto que como estamos realizando un pmv y en estos momentos del desarrollo no son necesarios no creo que sea conveniente añadirlos.

Así está perfecto! :100:

**Comment by MarinoFajardo** [comment]
Vale, te hago un push de la clase para que puedas ver el código.

**Comment by MarinoFajardo** [comment]
Te dejo unos comentarios con respecto al estándar de typescript:
-Los nombres de los ficheros se escriben con guion bajo entre palabras: recursos_humanos.ts
-Los nombres de las clases de escriben con la primera letra en mayúscula y si hay más de una palabra la primera letra es en mayúscula: class RecursosHumanos
-Los nombres de las variables se escriben en minúscula, si hay más de una palabra se unen escribiendo la primera letra de la segunda palabra en mayúscula: fechaNacimiento
-Las tabulaciones son de tamaño dos espacios.
-A diferencia de javascript hay que escrbir ; al final de cada línea.
-No usar los tipos Number, String, Boolean, Symbol, u Object, usar los tipos number, string, boolean, y symbol en minúscula.
