### ISSUE TITLE
[M0-Dev] Implementación del modelo referente a los curriculums.

### ISSUE THREAD

**Issue by MarinoFajardo** [aacosa34/Keikaku#12]
Buenas @aacosa34, he abierto este issue para crear una clase que represente a los currículums que va manejar el sistema. He pensado que esta clase tiene que tener los siguientes atributos:
-nombre:string
-apellidos:string
-fechaNacimiento:Date
-experiencia:string
-nivelIngles:Crear un enumerado con los distintos niveles de inglés(A1,A2,B1,B2,C1,C2)
-nivelEstudios:Crear un enumerado con los distintos niveles de estudio(Primaria,Secundaria,Bachillerato,FP,GradoSuperior,Grado,Máster).
Viendo esto, tenemos en común 3 atributos con la clase creada en el issue #11, por lo que se podría crear una clase abstracta que contuviese esos 3 atributos y a partir de la cual heredasen esta clase y la clase creada anteriormente. ¿Opto por esta implementación o no incorporo esta clase abstracta? Un Saludo.

**Comment by adacosdev** [comment]
> Buenas @aacosa34, he abierto este issue para crear una clase que represente a los currículums que va manejar el sistema. He pensado que esta clase tiene que tener los siguientes atributos: -nombre:string -apellidos:string -fechaNacimiento:Date -experiencia:string -nivelIngles:Crear un enumerado con los distintos niveles de inglés(A1,A2,B1,B2,C1,C2) -nivelEstudios:Crear un enumerado con los distintos niveles de estudio(Primaria,Secundaria,Bachillerato,FP,GradoSuperior,Grado,Máster). Viendo esto, tenemos en común 3 atributos con la clase creada en el issue #11, por lo que se podría crear una clase abstracta que contuviese esos 3 atributos y a partir de la cual heredasen esta clase y la clase creada anteriormente. ¿Opto por esta implementación o no incorporo esta clase abstracta? Un Saludo.

Según lo visto en el objetivo anterior, lo de la expriencia muchas veces no es muy significativo a la hora de aceptar a un candidato, por lo tanto optaría por quitarla. Lo que sí que debería de tener es un array de strings en el que se almacenen las características relevantes en cuanto a la oferta a la que aplica. Con esto me refiero a las tecnologías que aparecen en el currículum de la persona que aplica.

En cuanto a la herencia podríamos crear una superclase que fuese BasicData y que contenga los tres atributos mencionados. No me parece mala opción. Intenta implementarlo y lo veo en el PR.

**Comment by MarinoFajardo** [comment]
Buenas @aacosa34, acabo de implementar lo que hemos comentado, te hago un push y espero tu respuesta en el PR. Un saludo.
