### ISSUE TITLE
[M0-Dev] Hace falta una estructura de datos para definir las ofertas de empleo

### ISSUE THREAD

**Issue by adacosdev** [aacosa34/Keikaku#13]
La lógica de negocio consiste en que se rechaza directamente un currículum si no cumple un determinado número de requisitos. Por lo tanto es necesario que la oferta de empleo quede registrada de alguna manera. Se me ocurre que crear una clase en un nuevo fichero puede ser conveniente a la hora de que en ésta queden reflejados los currículums que han llegado por esa oferta de empleo específicamente.

Según ésto @MarinoFajardo, lo dejo en tus manos para que me propongas una solución!

**Comment by MarinoFajardo** [comment]
Buenas @aacosa34, para lo que me comentas se me ocurre crear una clase que se llame oferta con las siguientes variables:
-nombre:string
-descripcion:string
-fechaCreacion:Date
-TipoOferta:tipo enumerado
-curriculums: currículums[ ]
¿Te parece bien?. Un saludo.

**Comment by adacosdev** [comment]
Al TipoOferta le cambiaría el nombre a algo como "puesto" o algo así. De hacer un enumerado, ¿qué puestos contendría?

**Comment by MarinoFajardo** [comment]
Viendo lo que me has dicho realmente el enumerado tendía que tener los puestos de la empresa que fuese a usar la aplicación, por ejemplo, si fuese un restaurante podría ser cocinero, camarero, etc. Para hacerlo de una manera general se podría poner como puesto empleado, jefe de sección, encargado, jefe de personal, etc.

**Comment by adacosdev** [comment]
> Viendo lo que me has dicho realmente el enumerado tendía que tener los puestos de la empresa que fuese a usar la aplicación, por ejemplo, si fuese un restaurante podría ser cocinero, camarero, etc. Para hacerlo de una manera general se podría poner como puesto empleado, jefe de sección, encargado, jefe de personal, etc.

Me parece buena solución. :+1:
