### ISSUE TITLE
[M0-Dev] Mutabilidad de las Clases

### ISSUE THREAD

**Issue by MarinoFajardo** [aacosa34/Keikaku#14]
Buenas @aacosa34 he abierto este issue para aclarar los objetos valor y las entidades del proyecto. Con respecto a lo que hemos hecho hasta ahora pienso que en nuestro caso tenemos un objeto valor que es el currículum, ya que una vez creado no debería poder ser modificado mientras que el personal y las ofertas serían entidades ya que deberían poder ser modificadas. ¿Que opinas al respecto, te parece bien o lo habías pensado de otra forma?

**Comment by adacosdev** [comment]
Me parece perfecto. Yo había pensado lo mismo, los currículums sólo deben de ser objetos de lectura y nunca ser alterada su información. Sin embargo tanto el personal y las ofertas pueden ser modificables con el paso del tiempo debido a cambios de contraseña, correo, etc. por parte del personal, y en las ofertas podría alterarse la descripción o el título con el fin de que se afine más la búsqueda de nuevos empleados o símplemente que se aclare la información.

**Comment by MarinoFajardo** [comment]
Perfecto, pues voy a crear el archivo iv.yaml con estos datos.
