### ISSUE TITLE
[M0-DEV]Elección del Lenguaje de programación

### ISSUE THREAD

**Issue by MarinoFajardo** [aacosa34/Keikaku#15]
Elección del Lenguaje de programación

_Originally posted by @MarinoFajardo in https://github.com/aacosa34/Keikaku/issues/7#issuecomment-1293349467_

**Comment by MarinoFajardo** [comment]
Hola @aacosa34, como desarrollador necesito conocer el lenguaje de programación que vamos a usar en el proyecto. ¿Tienes alguno en mente?. Un saludo.

**Comment by adacosdev** [comment]
El lenguaje de programación que quiero usar para desarrollar para este projecto es TypeScript en su última version (4.8.4) ya que tengo un conocimiento previo de JavaScript y me encantaría aprenderlo.

Para su ejecución en el lado del servidor quiero usar Node.js en su version 18.12 ya que es uno de runtime de javascript más extendido y también me gustaría aprender a usarlo.

**Comment by MarinoFajardo** [comment]
Perfecto
