### ISSUE TITLE
[M0-DEV]Concepto de Currículum

### ISSUE THREAD

**Issue by MarinoFajardo** [aacosa34/Keikaku#16]
Referente a #7 ¿Qué es un currículum? es decir, ¿Cómo se va a usar y cómo va a ser este concepto aplicado posteriormente en la lógica de negocio?¿Quė  se va a usar para crear un ranking de currículums?.¿En qué formato se van a almacenar los currículums en el sistema?,¿Todos ellos van a seguir el mismo formato?
Con respecto al formato, he decidido que todos los currículums del sistema se representen en formato PDF ya que es el formato más usado, por lo que la información obtenida de los PDF de los currículums vendrá en formato texto y será así para todos los currículums del sistema. De esta manera los currículums serán objetos inmutables una vez son creados y representarán nuestros objetos valor.

**Comment by MarinoFajardo** [comment]
Buenas @aacosa34 , abro este issue para saber a que nos referimos con un curriculum.

**Comment by adacosdev** [comment]
La información que contiene un currículum va a utilizarse para que se pueda comprobar que la persona que aplica a una oferta de trabajo efectivamente cumple los requisitos de dicha oferta y se pueda tener en cuenta para ésta.

Lo más importante para cada oferta de trabajo va a ser la experiencia que tiene en el puesto ofertado. A partir de ahí, a igualdad de experiencia, tendremos en cuenta el nivel de estudios. Y si ambos son iguales, tendremos en cuenta el nivel de inglés.

**Comment by JJ** [comment]
¿Cómo se va a usar esta información en la lógica de negocio?
Lo que tiene que contestar @aacosa34 es eso, no lo que piense que suele estar en un currículum. Se trata de hacer un modelo del problema, no un mandao.

**Comment by JJ** [comment]
> ¿Cómo se va a usar esta información en la lógica de negocio? Lo que tiene que contestar @aacosa34 es eso, no lo que piense que suele estar en un currículum. Se trata de hacer un modelo del problema, no un mandao.

No habéis contestado a esto. No hay ningún intento de aplicar un mapeado de dominio al problema y su lógica de negocio. Simplemente se ha eliminado un atributo y se ha fusionado otro. ¿De qué manera eliminar el puesto y convertir nombre y apellidos en un solo atributo satisface el concepto de currículum? @aacosa34 ¿vas a poder usar el resultado en el objetivo 4, cuando tengas que programar la lógica de negocio? ¿Hortensia (#7 ) va a ser capaz de encontrar la persona adecuada para un puesto con el nivel de inglés (y sólo de inglés) y la fecha de nacimiento? ¿Hay puestos de trabajo que requieran que se haya nacido en una fecha determinada?

**Comment by MarinoFajardo** [comment]
> ¿De qué manera eliminar el puesto y convertir nombre y apellidos en un solo atributo satisface el concepto de currículum?

Con respecto a esto, es verdad que no se va a elegir a un candidato por su nombre y apellidos.

> ¿Hortensia (https://github.com/aacosa34/Keikaku/issues/7 ) va a ser capaz de encontrar la persona adecuada para un puesto con el nivel de inglés (y sólo de inglés) y la fecha de nacimiento? ¿Hay puestos de trabajo que requieran que se haya nacido en una fecha determinada?

 Siendo realistas los datos personales no son relevantes en la lógica de negocio a la hora de elegir un candidato.

**Comment by MarinoFajardo** [comment]
En el commit [415c986](https://github.com/aacosa34/Keikaku/pull/10/commits/415c9863ca0ad4f30a40b65364f1fe317436739b) he aplicado lo que hemos hablado aplicando la lógica de negocio ya que los datos personales no son relevantes a la hora de elegir un candidato. Para que Hortensia #7 pueda encontrar el candidato apropiado se deberá tener en cuenta si el candidato posee carnet de conducir, su nivel de inglés y de estudios y si cumple una serie de aptitudes.

**Comment by adacosdev** [comment]
> En el commit [415c986](https://github.com/aacosa34/Keikaku/pull/10/commits/415c9863ca0ad4f30a40b65364f1fe317436739b) he aplicado lo que hemos hablado aplicando la lógica de negocio ya que los datos personales no son relevantes a la hora de elegir un candidato. Para que Hortensia #7 pueda encontrar el candidato apropiado se deberá tener en cuenta si el candidato posee carnet de conducir, su nivel de inglés y de estudios y si cumple una serie de aptitudes.

Me parece una buena decisión ya sobraban campos a la hora de aplicar la lógica de negocio. No se puede aceptar o rechazar en función del nombre y apellidos o de la fecha de nacimiento de una persona. 

> ¿De qué manera eliminar el puesto y convertir nombre y apellidos en un solo atributo satisface el concepto de currículum? @aacosa34 ¿vas a poder usar el resultado en el objetivo 4, cuando tengas que programar la lógica de negocio? ¿Hortensia (https://github.com/aacosa34/Keikaku/issues/7 ) va a ser capaz de encontrar la persona adecuada para un puesto con el nivel de inglés (y sólo de inglés) y la fecha de nacimiento? ¿Hay puestos de trabajo que requieran que se haya nacido en una fecha determinada?

Me parece que el commit que se ha hecho responde muy bien a estas preguntas ya que se ha quitado lo innecesario para la lógica de negocio.

**Comment by JJ** [comment]
> La información que contiene un currículum va a utilizarse para que se pueda comprobar que la persona que aplica a una oferta de trabajo efectivamente cumple los requisitos de dicha oferta y se pueda tener en cuenta para ésta.
> 

Eso no es un currículum. Es una serie de requisitos. Si es eso lo que buscas, no es un currículum lo que quieres.

> Lo más importante para cada oferta de trabajo va a ser la experiencia que tiene en el puesto ofertado. A partir de ahí, a igualdad de experiencia, tendremos en cuenta el nivel de estudios. Y si ambos son iguales, tendremos en cuenta el nivel de inglés.

¿Dónde dice eso en la lógica de negocio o en el milestone en el que se está trabajando?

**Comment by adacosdev** [comment]
> Eso no es un currículum. Es una serie de requisitos. Si es eso lo que buscas, no es un currículum lo que quieres.

A ver, lo que yo conozco de un currículum es que es una especificación de toda la experiencia que tiene una persona en el mundo laboral además de sus estudios y conocimientos. Cuando alguien aplica a una empresa, lo que la empresa espera de esa persona es que en su currículum ponga que tiene alguna aptitud/experiencia/conocimiento que pueda utilizar a la hora de trabajar en la empresa. Por lo tanto no me parece una idea muy disparatada el uso de un "currículum" para poder comprobar unos conocimientos mínimos, unos estudios mínimos o una experiencia mínima previa.

Por lo tanto la información de un currículum se podrá usar en la oferta de trabajo para saber si una persona es apta o no para el puesto que se oferta, a mi parecer.

> ¿Dónde dice eso en la lógica de negocio o en el milestone en el que se está trabajando?

Eso no incumbe a este milestone realmente. Esa información será necesaria despues en el milestone 1.

**Comment by JJ** [comment]
A ver si nos entendemos. El concepto de milestone y de historia de usuario es para ayudar al equipo de desarrollo a entender de qué se trata el problema y poder empezar a resolverlo. Si tiene que preguntarte el equipo de desarrollo "meto esto o aquello" estáis los dos perdiendo el tiempo. Más todavía si propone algo y tienes que decirle "Ah, no, es que eso no tenía pensado meterlo".

La persona que trabaje en el desarrollo, como ya dije en #18, tiene que tener la información adecuada para comenzar a trabajar. Aparentemente, el concepto de "información para trabajar" es diferente en vuestro caso y en el mío, pero lo cierto es que lo que se está haciendo no sigue una metodología sistemática de resolución de problemas. Sin una metodología sistemática, simplemente no se puede trabajar, porque ¿cómo va a saber la persona que la lógica de negocio va a usar el nivel de estudios? En la historia de usuario tiene que poner todo lo que se vaya a tener en cuenta, de forma que se haga un *modelo*. Y ese modelo sea *lo más abstracto posible*, porque si mañana en vez de nivel de estudios se decide usar certificaciones, **no haya que añadir otro atributo en el objeto y cambiarlo todo**. Programar es modelizar, y modelizar implica entender el problema: plantearlo bien por todas las partes, y tratar de resolverlo.

Así que os rogaría, por favor, que revisárais los objetivos de aprendizaje de estas semanas pasadas, también explicados en clase, donde se hizo mucho énfasis en que sólo se tiene que desarrollar lo que se pida en HU y en milestones, *y sólo eso*.

Por otra parte, @aacosa34, te recuerdo que la lógica de negocio tiene que ir más allá de mirar "primero a los estudios y luego a la experiencia". Tiene que ser un algoritmo con cierta sustancia. 

Te recuerdo que en la descripción de la lógica de negocio pone:

> Además es una solución muy flexible ya que en función de la empresa o de la oferta se puede adaptar a las necesidades de ésta sin esfuerzo.

¿Sin esfuerzo es reprogramar todo el proyecto desde abajo si hace falta chino en vez de inglés? ¿Tendrás que poner eso en una historia de usuario?
