### ISSUE TITLE
[M0-DEV] Concepto de Oferta de Trabajo

### ISSUE THREAD

**Issue by MarinoFajardo** [aacosa34/Keikaku#17]
En la Historia de Usuario #7 también aparece el concepto de oferta de trabajo. ¿Cómo se va a usar este cocepto y cómo se va a aplicar en la lógica de negocio?¿Una oferta de trabajo tendrá asignados una serie de currículums?¿Cómo se almacenarán los requisitos que posee una oferta?
Con respecto a lo anterior he decidido que las ofertas posean una colección de currículums para que así con tu lógica de negocio puedas ir eliminado los currículums que no cumplan los requisitos mínimos que hemos visto en #19 .

**Comment by adacosdev** [comment]
Una oferta de trabajo va a definir en la lógica de negocio qué currículums se quedan en el sistema y qué currículums no en función los requisitos para aplicar a la propia oferta.

**Comment by JJ** [comment]
> Viendo la historia de usuario #7 , nos aparece el concepto de oferta de trabajo, he pensado que una oferta de trabajo contiene una colección de currículums donde se aplicará tu lógica de negocio para obtener los curriculums que cumplan una serie de requisitos mínimos y los currículums que se adapten mejor a la oferta.

No tienes que "pensar" nada y proponérselo a @aacosa34 . Tienes que entender cómo se modeliza el problema para poder aplicarle la lógica de negocio.

**Comment by JJ** [comment]
> Una oferta de trabajo contendrá, como bien comentas, el conjunto de todos los currículums de las personas que aplican a dicha oferta almacenados en un array del tipo Currículums como mencionamos en #16. También contendrá el nombre de la oferta, la descripción de dicha oferta y los requisitos que son obligatorios e indispensables para poder valorar que si un currículum no contiene dichos criterios, se rechace directamente.

Te cuesta el mismo trabajo decir cómo se implementa que implementarlo. Para eso no hacen falta dos personas.

**Comment by MarinoFajardo** [comment]
En el commit [e17d086](https://github.com/aacosa34/Keikaku/pull/10/commits/e17d086125bc0d277c91dda4daa64976dce6110e) al igual que en la clase currículum he eliminado los datos descriptivos de la oferta ya que no son relevantes a la hora de filtrar los curriculums y he añadido array de palabras clave que serán los criterios mínimos que tiene que cumplir un curriculum para no ser descartado del sistema.

**Comment by JJ** [comment]
Los issues deben plantear problemas, y plantearlos *en el cuerpo del issue*, que es la referencia, no en comentarios al mismo.
