### ISSUE TITLE
La formulación del milestone 0 no es adecuada para el comienzo del desarrollo del producto

### ISSUE THREAD

**Issue by JJ** [aacosa34/Keikaku#18]
[Este milestone](https://github.com/aacosa34/Keikaku/milestone/2) habla de (1) "módulo", sin indicar qué tipo de problema hay que resolver ni qué fase de desarrollo del problema significa. En parte culpa mía, porque pensé que al escribir eso la persona que lo escribió entendía en qué consistía en el modelo 0, el hecho de que quien haya empezado a desarrollar con esa guía no encuentre el camino evidencia que *no* se trata de tal guía, y por tanto no contesta a la pregunta básica del desarrollo, que es "¿Qué tengo que hacer ahora?" y "¿Lo que hago está bien?"

**Comment by adacosdev** [comment]
He hecho cambios en la descripción del milestone. Creo que ahora está mejor definido el "¿Qué tengo que hacer ahora?" y si "¿Lo que hago está bien?"

> ¿Qué tengo que hacer ahora?

Para contestar ésta pregunta he descrito que lo que debe hacerse para completarse el milestone es modelar las ofertas de trabajo y los currículums.

> ¿Lo que hago está bien?

Para saber si se han modelado bien he comentado lo que debe representar un currículum y una oferta de trabajo al finalizar el desarrollo del milestone.

No sé si debo ser más especifico con lo que tendrían que contener cada uno.

**Comment by JJ** [comment]
Quieres uno (1) módulo. Ajá. ¿Qué es para ti un módulo? ¿Por qué tiene que ser un módulo? ¿Por qué decides de antemano qué es lo que hay que modelar y no dejar que sea el propio modelado el que decida qué es importante y qué no?
En todo caso, cuando esté todo correcto, tendrás que hacer un cambio en la descripción del milestone en el repositorio que cierre este issue.

**Comment by adacosdev** [comment]
> ¿Qué es para ti un módulo? ¿Por qué tiene que ser un módulo?

Realmente quiero que sean dos ficheros que contengan las dos clases que quiero que se implementen.

> ¿Por qué decides de antemano qué es lo que hay que modelar y no dejar que sea el propio modelado el que decida qué es importante y qué no?

Eso hay que decidirlo en el DDD, no en el milestone como tengo puesto.

Acabo de modificarlo de nuevo.

**Comment by JJ** [comment]
> > ¿Qué es para ti un módulo? ¿Por qué tiene que ser un módulo?
> 
> Realmente quiero que sean dos ficheros que contengan las dos clases que quiero que se implementen.
> 

Un milestone *nunca* tiene detalles de implementación. Lo que importa no es el número de ficheros, sino el producto. Si son 3, ¿el producto sería inválido?

**Comment by adacosdev** [comment]
> Si son 3, ¿el producto sería inválido?

No tiene por qué, en el milestone no digo el número de ficheros que hacen falta para completarlo.

**Comment by JJ** [comment]
Ahora no dice *dónde* hay que definirlo; es decir, no dice qué hace el producto viable.

**Comment by adacosdev** [comment]
> Ahora no dice _dónde_ hay que definirlo; es decir, no dice qué hace el producto viable.

No entiendo a qué te refieres. En el título digo que se haga en distintos ficheros.

**Comment by JJ** [comment]
> > Ahora no dice _dónde_ hay que definirlo; es decir, no dice qué hace el producto viable.
> 
> No entiendo a qué te refieres. En el título digo que se haga en distintos ficheros.

¿Te parece una condición suficiente para la viabilidad? ¿Si es un solo fichero no es viable? ¿Sólo lo hace viable el que sea en "distintos ficheros"? Si yo pongo en un fichero

```text
definición de x: es una cosa que hace y
```

¿ya es viable, o no lo es porque está en un solo fichero y no en *distintos*?

**Comment by adacosdev** [comment]
> ¿ya es viable, o no lo es porque está en un solo fichero y no en _distintos_?

Realmente me da igual en cuántos ficheros se realice, quiero que quede bien representado lo que es una oferta de trabajo y un currículum que es la base del proyecto. A partir de ahí me da igual que sea en uno o varios ficheros y que sea una clase o un struct o lo que sea. El objetivo principal del milestone yo creo que es claro, lo que no se es cómo poner que esté representado como producto informático porque no sé cómo no limitar al programador a que lo haga en la cantidad de ficheros que él crea conveniente.

Podría poner que sea en un/unos fichero/s, por ejemplo?

**Comment by JJ** [comment]
Puedes poner qué es lo que los hace viables, que es como se especifica un PMV. Consulta el material que se ha dado sobre el mismo, si es necesario.

**Comment by adacosdev** [comment]
> Puedes poner qué es lo que los hace viables, que es como se especifica un PMV. Consulta el material que se ha dado sobre el mismo, si es necesario.

He mirado el material de la asignatura sobre los PMV y he adaptado un poco más el milestone, creo que ahora está mejor definido el qué quiero como producto informático y se especifíca cómo saber si se está haciendo bien.

**Comment by JJ** [comment]
> > Puedes poner qué es lo que los hace viables, que es como se especifica un PMV. Consulta el material que se ha dado sobre el mismo, si es necesario.
> 
> He mirado el material de la asignatura sobre los PMV y he adaptado un poco más el milestone, creo que ahora está mejor definido el qué quiero como producto informático y se especifíca cómo saber si se está haciendo bien.

Pregúntale a @marinofajardo si es suficiente...

**Comment by adacosdev** [comment]
Acabo de modificarlo de nuevo, no se si ahora estará mejor.

**Comment by MarinoFajardo** [comment]
Tras la ultima modificación de @aacosa34, yo creo que el milestone 0 está correcto, en él se pide crear una representación del modelo del problema referente a las ofertas y los currículums y para que sea viable se pide que lo que se cree compile de manera correcta.

**Comment by adacosdev** [comment]
@JJ está bien formulado ya entonces?

**Comment by JJ** [comment]
Si sirve para @MarinoFajardo, es que está bien.
