### ISSUE TITLE
[M0-Dev] Concepto de Requisitos Mínimos

### ISSUE THREAD

**Issue by MarinoFajardo** [aacosa34/Keikaku#19]
En la Historia de Usuario #7 se nos comenta que Hortensia pierde mucho tiempo seleccionando los curriculums que cumplen una serie de requisitos mínimos, ¿cuáles son estos requisitos mínimos que debe cumplir un currículum y como se van a usar?

**Comment by adacosdev** [comment]
En la lógica de negocio se contemplan los requisitos mínimos como los campos que tiene que tener obligatoriamente un currículum para no ser eliminado del sistema.
