### ISSUE TITLE
[M0-Dev] Elección del lenguaje de Programación.

### ISSUE THREAD

**Issue by MarinoFajardo** [aacosa34/Keikaku#8]
Hola @aacosa34, me han asignado tu repositorio para el objetivo 2. Lo primero que debemos debatir es el lenguaje de programación en el que deseas realizar el proyecto y para eso he abierto este issue. Un saludo.

**Comment by adacosdev** [comment]
El lenguaje que usaremos será TypeScript en su versión 4.8.4 sobre Node.js en su version 16.17.

**Comment by adacosdev** [comment]
Acabo de ver que en los recursos aportados en la asignatura se habla sobre typescript y recomendaciones de uso. El link es el siguiente: https://jj.github.io/IV/documentos/proyecto/2.Entidad.recursos.html

Sería conveniente mirarlos y valorar si hay que cambiar algo en cuanto al entorno de ejecución, que inicialmente tenía pensado que fuera node.js
