### ISSUE TITLE
[M0-Dev] Estructura de Carpetas y Ficheros.

### ISSUE THREAD

**Issue by MarinoFajardo** [aacosa34/Keikaku#9]
Buenas @aacosa34, ¿cómo organizo las carpetas y los ficheros de la aplicación? Un Saludo.

**Comment by MarinoFajardo** [comment]
https://www.typescripttutorial.net/typescript-tutorial/nodejs-typescript/ en este enlace se recomienda crear una carpeta principal para el proyecto y dentro de ella crear dos subcarpetas, la carpeta src donde se almacenan el código typescript y la carpera build  donde se almacenan los ficheros que se nos generan al compilar el código. ¿Te parece correcto?

**Comment by adacosdev** [comment]
Me parece perfecto. La carpeta principal en este caso va a ser la del repositorio como tal y ahi hay que crear ambas carpetas.

**Comment by MarinoFajardo** [comment]
Vale, entonces te creo las dos subcarpetas dentro del repositorio.

**Comment by MarinoFajardo** [comment]
Para la configuración de node con javascript he creado un archivo en la carpeta principal llamado tsconfig.json que contiene la configuración para compilar los archivos de typescript, de esta manera desde la carpeta principal haciendo tsc en el terminal se compilan los archivos que se encuentren en la carpeta src y se crean los ficheros compilados en la carpeta build. ¿Te parece bien? Un Saludo.

**Comment by adacosdev** [comment]
Estupendo. Por cierto, todavía no has abierto el PR en mi repo. Estaría guay poder ir viendo los archivos que vas metiendo y poder comentarte también en el PR.

**Comment by MarinoFajardo** [comment]
Pues te hago ahora un push que ya tenemos esto creado y así puedes ir viendo todo.
